/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author shahin
 * 
 * Main class that drives GUI. This file creates a CPU object 
 * and runs the computer by making repeated calls to that object.
 */

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;

import javax.swing.Timer;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.*;
 
import java.util.logging.Logger;

public class MachineSimulator extends javax.swing.JFrame {
    
    // Global Vars
    CPU main_CPU;
    int[] in_button_array = new int[]{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
    int[] default_PC_loc = new int[]{0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0};
    boolean run_check = false;
    String search = "";
    String search_text = "";
    int count=1;
    
    /* 
    Function that runs the gui and CPU
    IN: N/A
    OUT: N/A
    */
    public MachineSimulator() {
        initComponents();
        main_CPU = new CPU();
        int[] tmp_val = {0,0,0,0,0,0,0,0,0,1,1,0};
        main_CPU.setRegisterValue("PC",tmp_val);
        new Timer(delay, mainLoop).start();
    }
    
    // Main loop of the program that runs every 500 mil
    int delay = 50; //milliseconds
    ActionListener mainLoop = new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            
            // Update Registers for display
            updateRegisters();
            
            // Handle Flags
            if (main_CPU.getRegisterValue("IOWAIT")[0] != 0){
                System.out.println();
                System.out.println(main_CPU.getRegisterValue("IOWAIT")[0]);
                System.out.println(formatText(main_CPU.getRegisterValue("IOWAIT")));
                updateKeyboard();
                System.out.println("IOWAIT");
                int [] msg1 = new int[]{0};
                main_CPU.setRegisterValue("IOWAIT", msg1);
                System.out.println(formatText(main_CPU.getRegisterValue("IOWAIT")));
            }
            if (main_CPU.getRegisterValue("PRINT_FLAG")[0] == 1){
                updatePrinter();
                int [] msg = new int[]{0};
                main_CPU.setRegisterValue("PRINT_FLAG", msg);
            }
            // Check if machine is set to run
            if (run_check){
           
                main_CPU.execute("single");
                // If running, check if halt flag is raised
                if (main_CPU.getRegisterValue("HLT")[0] == 1 || main_CPU.getRegisterValue("HLT")[0] == 2){
                    
                    // Make program 2 here
                    if (main_CPU.getRegisterValue("HLT")[0] == 2){
                        // This reads in the CARD.txt
                      
                        proccessText();
                     
             
                        // Put your search function that searches through search_text for search here.

                        // This prints to the console printer
                   
                    }
                    run_check = false;
                    int [] msg = new int[]{0};
                    main_CPU.setRegisterValue("HLT",msg);
                }
            }
        }
    };
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        toggle15 = new javax.swing.JToggleButton();
        toggle14 = new javax.swing.JToggleButton();
        toggle13 = new javax.swing.JToggleButton();
        toggle12 = new javax.swing.JToggleButton();
        toggle11 = new javax.swing.JToggleButton();
        toggle10 = new javax.swing.JToggleButton();
        toggle9 = new javax.swing.JToggleButton();
        toggle8 = new javax.swing.JToggleButton();
        toggle7 = new javax.swing.JToggleButton();
        toggle6 = new javax.swing.JToggleButton();
        toggle5 = new javax.swing.JToggleButton();
        toggle4 = new javax.swing.JToggleButton();
        toggle3 = new javax.swing.JToggleButton();
        toggle2 = new javax.swing.JToggleButton();
        toggle1 = new javax.swing.JToggleButton();
        toggle0 = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        PCTextfField = new javax.swing.JTextField();
        MARTextField = new javax.swing.JTextField();
        MBRTextField = new javax.swing.JTextField();
        IRTextField = new javax.swing.JTextField();
        MFRTextField = new javax.swing.JTextField();
        PCLoadButton = new javax.swing.JButton();
        MARLoadButton = new javax.swing.JButton();
        IRLoadButton = new javax.swing.JButton();
        MBRLoadButton = new javax.swing.JButton();
        CCTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        GPR0TextField = new javax.swing.JTextField();
        GPR1TextField = new javax.swing.JTextField();
        GPR2TextField = new javax.swing.JTextField();
        GPR3TextField = new javax.swing.JTextField();
        IXR1TextField = new javax.swing.JTextField();
        IXR2TextField = new javax.swing.JTextField();
        IXR3TextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        GPR0LoadButton = new javax.swing.JButton();
        GPR1LoadButton = new javax.swing.JButton();
        GPR2LoadButton = new javax.swing.JButton();
        GPR3LoadButton = new javax.swing.JButton();
        IXR1LoadButton = new javax.swing.JButton();
        IXR2LoadButton = new javax.swing.JButton();
        IXR3LoadButton = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        Mem_2ValueTextField = new javax.swing.JTextField();
        Mem_1ValueTextField = new javax.swing.JTextField();
        Mem0ValueTextField = new javax.swing.JTextField();
        Mem1ValueTextField = new javax.swing.JTextField();
        Mem2ValueTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Mem_2RowTextField = new javax.swing.JTextField();
        Mem_1RowTextField = new javax.swing.JTextField();
        Mem1RowTextField = new javax.swing.JTextField();
        Mem2RowTextField = new javax.swing.JTextField();
        Mem0RowTextField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        RunButton = new javax.swing.JButton();
        IPLLoadButton = new javax.swing.JButton();
        STPLoadButton = new javax.swing.JButton();
        STLoadButton = new javax.swing.JButton();
        SingleStepButton = new javax.swing.JButton();
        HaltButton = new javax.swing.JToggleButton();
        LoadLoadButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JToggleButton();
        KeyboardTextField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PrinterTextArea = new javax.swing.JTextArea();
        KeyboardReadButton = new javax.swing.JButton();
        ConsoleTextField = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jLabel19.setText("Operation");

        jLabel21.setText("IXR");

        jLabel22.setText("I");

        jLabel23.setText("Address");

        jLabel20.setText("GPR");

        toggle15.setText("15");
        toggle15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggle15ActionPerformed(evt);
            }
        });

        toggle14.setText("14");
        toggle14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggle14ActionPerformed(evt);
            }
        });

        toggle13.setText("13");
        toggle13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggle13ActionPerformed(evt);
            }
        });

        toggle12.setText("12");
        toggle12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggle12ActionPerformed(evt);
            }
        });

        toggle11.setText("11");
        toggle11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggle11ActionPerformed(evt);
            }
        });

        toggle10.setText("10");
        toggle10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggle10ActionPerformed(evt);
            }
        });

        toggle9.setText("09");
        toggle9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggle9ActionPerformed(evt);
            }
        });

        toggle8.setText("08");
        toggle8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggle8ActionPerformed(evt);
            }
        });

        toggle7.setText("07");
        toggle7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggle7ActionPerformed(evt);
            }
        });

        toggle6.setText("06");
        toggle6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggle6ActionPerformed(evt);
            }
        });

        toggle5.setText("05");
        toggle5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggle5ActionPerformed(evt);
            }
        });

        toggle4.setText("04");
        toggle4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggle4ActionPerformed(evt);
            }
        });

        toggle3.setText("03");
        toggle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggle3ActionPerformed(evt);
            }
        });

        toggle2.setText("02");
        toggle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggle2ActionPerformed(evt);
            }
        });

        toggle1.setText("01");
        toggle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggle1ActionPerformed(evt);
            }
        });

        toggle0.setText("00");
        toggle0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggle0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(toggle15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toggle14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toggle13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toggle12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toggle11)
                .addGap(6, 6, 6)
                .addComponent(toggle10)
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(toggle9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toggle8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(toggle7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toggle6))
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggle5))
                .addGap(29, 29, 29)
                .addComponent(toggle4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toggle3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(toggle2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toggle1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toggle0))
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toggle15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggle14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggle13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggle12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggle11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggle10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggle9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggle8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggle7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggle6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggle5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggle4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggle3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggle2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggle1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggle0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel20))
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel8.setText("PC");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel9.setText("MAR");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel10.setText("MBR");

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel11.setText("IR");

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel12.setText("MFR");

        PCTextfField.setText("jTextField8");
        PCTextfField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCTextfFieldActionPerformed(evt);
            }
        });

        MARTextField.setText("jTextField9");

        MBRTextField.setText("jTextField10");

        IRTextField.setText("jTextField11");

        MFRTextField.setText("jTextField12");

        PCLoadButton.setLabel("Load");
        PCLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCLoadButtonActionPerformed(evt);
            }
        });

        MARLoadButton.setLabel("Load");
        MARLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MARLoadButtonActionPerformed(evt);
            }
        });

        IRLoadButton.setLabel("Load");
        IRLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IRLoadButtonActionPerformed(evt);
            }
        });

        MBRLoadButton.setLabel("Load");
        MBRLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MBRLoadButtonActionPerformed(evt);
            }
        });

        CCTextField.setText("jTextField12");

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel13.setText("CC");

        jLabel27.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel27.setText("Register Value");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(5, 5, 5))
                                    .addComponent(jLabel12))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(MARTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(MFRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(MBRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CCTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MARLoadButton)
                            .addComponent(MBRLoadButton)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel27)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(PCTextfField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(PCLoadButton))))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(IRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(IRLoadButton))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PCLoadButton)
                    .addComponent(PCTextfField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IRLoadButton)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MARTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(MARLoadButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MBRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(MBRLoadButton))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MFRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(CCTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel7.setText("IXR 3");

        GPR0TextField.setText("jTextField1");

        GPR1TextField.setText("jTextField2");
        GPR1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPR1TextFieldActionPerformed(evt);
            }
        });

        GPR2TextField.setText("jTextField3");

        GPR3TextField.setText("jTextField4");

        IXR1TextField.setText("jTextField5");

        IXR2TextField.setText("jTextField6");

        IXR3TextField.setText("jTextField7");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("GPR 0");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setText("GPR 1");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setText("GPR 2");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setText("GPR 3");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setText("IXR 1");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setText("IXR 2");

        GPR0LoadButton.setLabel("Load");
        GPR0LoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPR0LoadButtonActionPerformed(evt);
            }
        });

        GPR1LoadButton.setLabel("Load");
        GPR1LoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPR1LoadButtonActionPerformed(evt);
            }
        });

        GPR2LoadButton.setLabel("Load");
        GPR2LoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPR2LoadButtonActionPerformed(evt);
            }
        });

        GPR3LoadButton.setLabel("Load");
        GPR3LoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPR3LoadButtonActionPerformed(evt);
            }
        });

        IXR1LoadButton.setLabel("Load");
        IXR1LoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IXR1LoadButtonActionPerformed(evt);
            }
        });

        IXR2LoadButton.setLabel("Load");
        IXR2LoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IXR2LoadButtonActionPerformed(evt);
            }
        });

        IXR3LoadButton.setLabel("Load");
        IXR3LoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IXR3LoadButtonActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel26.setText("Register Value");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IXR1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IXR1LoadButton))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(GPR3TextField))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(GPR2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel26)
                                        .addComponent(GPR0TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GPR1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GPR0LoadButton)
                            .addComponent(GPR1LoadButton)
                            .addComponent(GPR2LoadButton)
                            .addComponent(GPR3LoadButton)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IXR2TextField)
                            .addComponent(IXR3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IXR2LoadButton)
                            .addComponent(IXR3LoadButton))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GPR0TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GPR0LoadButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(GPR1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GPR1LoadButton))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(GPR2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GPR2LoadButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(GPR3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GPR3LoadButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(IXR1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IXR1LoadButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(IXR2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IXR2LoadButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IXR3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(IXR3LoadButton))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        Mem_2ValueTextField.setText("jTextField1");

        Mem_1ValueTextField.setText("jTextField2");

        Mem0ValueTextField.setText("jTextField3");

        Mem1ValueTextField.setText("jTextField4");

        Mem2ValueTextField.setText("jTextField5");

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel14.setText("Memory Location - 2");

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel15.setText("Memory Location - 1");

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel16.setText("MAR Location");

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel17.setText("Memory Location + 1");

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel18.setText("Memory Location + 2");

        Mem_2RowTextField.setText("jTextField1");

        Mem_1RowTextField.setText("jTextField1");

        Mem1RowTextField.setText("jTextField1");

        Mem2RowTextField.setText("jTextField1");

        Mem0RowTextField.setText("jTextField1");

        jLabel24.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel24.setText("Mem. Row");

        jLabel25.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel25.setText("Mem. Value");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(21, 21, 21)
                            .addComponent(Mem_1RowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Mem2RowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Mem1RowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Mem0RowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel24)
                                    .addGap(11, 11, 11))
                                .addComponent(Mem_2RowTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Mem1ValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Mem_2ValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Mem2ValueTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Mem_1ValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mem0ValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel25))
                    .addContainerGap(12, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Mem_2ValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Mem_2RowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(Mem_1ValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Mem_1RowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Mem0ValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(Mem0RowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Mem1ValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(Mem1RowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(Mem2ValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Mem2RowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(51, Short.MAX_VALUE)))
        );

        RunButton.setText("Run");
        RunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunButtonActionPerformed(evt);
            }
        });

        IPLLoadButton.setText("IPL");
        IPLLoadButton.setActionCommand("Store");
        IPLLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IPLLoadButtonActionPerformed(evt);
            }
        });

        STPLoadButton.setActionCommand("ST+");
        STPLoadButton.setLabel("ST+");
        STPLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STPLoadButtonActionPerformed(evt);
            }
        });

        STLoadButton.setLabel("Store");
        STLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STLoadButtonActionPerformed(evt);
            }
        });

        SingleStepButton.setLabel("SS");
        SingleStepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingleStepButtonActionPerformed(evt);
            }
        });

        HaltButton.setLabel("Halt");
        HaltButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HaltButtonActionPerformed(evt);
            }
        });

        LoadLoadButton.setText("Load");
        LoadLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadLoadButtonActionPerformed(evt);
            }
        });

        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(IPLLoadButton)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(STPLoadButton)
                            .addGap(18, 18, 18)
                            .addComponent(STLoadButton)
                            .addGap(18, 18, 18)
                            .addComponent(LoadLoadButton))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(SingleStepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(HaltButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RunButton))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IPLLoadButton)
                        .addComponent(STPLoadButton)
                        .addComponent(STLoadButton)
                        .addComponent(LoadLoadButton))
                    .addGap(21, 21, 21)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(SingleStepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(ResetButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(RunButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(HaltButton)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );

        KeyboardTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeyboardTextFieldActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel28.setText("Console Printer");

        jLabel29.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel29.setText("Console Keyboard");

        PrinterTextArea.setColumns(20);
        PrinterTextArea.setRows(5);
        jScrollPane1.setViewportView(PrinterTextArea);

        KeyboardReadButton.setText("Store");
        KeyboardReadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeyboardReadButtonActionPerformed(evt);
            }
        });

        ConsoleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsoleTextFieldActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel30.setText("Item Stored");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1339, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(KeyboardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KeyboardReadButton))
                    .addComponent(ConsoleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(KeyboardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(KeyboardReadButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ConsoleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunButtonActionPerformed
        // TODO add your handling code here:
        if (run_check == false){
            run_check = true;
        }else{
            run_check = false;
        }
    }//GEN-LAST:event_RunButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        // Reset registers
        int[] Reset_large = new int[]{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
        int[] Reset_medium = new int[]{0,0,0,0,0,0,0,0,0,0,0,0};
        int[] Reset_small = new int[]{0,0,0,0};

        main_CPU.setRegisterValue("IR", Reset_large);
        main_CPU.setRegisterValue("MBR", Reset_large);
        main_CPU.setRegisterValue("X1", Reset_large);
        main_CPU.setRegisterValue("X2", Reset_large);
        main_CPU.setRegisterValue("X3", Reset_large);
        main_CPU.setRegisterValue("GPR3", Reset_large);
        main_CPU.setRegisterValue("GPR0", Reset_large);
        main_CPU.setRegisterValue("GPR1", Reset_large);
        main_CPU.setRegisterValue("GPR2", Reset_large);

        main_CPU.setRegisterValue("PC", Reset_medium);
        main_CPU.setRegisterValue("MAR", Reset_medium);

        main_CPU.setRegisterValue("CC", Reset_small);
        main_CPU.setRegisterValue("MFR", Reset_small);
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void LoadLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadLoadButtonActionPerformed
        // Set MBR equal to the value located at MAR in memory
        int[] cur_MAR = main_CPU.getRegisterValue("MAR");
        int trans_MAR = main_CPU.binaryToInt(cur_MAR);
        main_CPU.setRegisterValue("MBR", main_CPU.getMemoryValue(trans_MAR));
    }//GEN-LAST:event_LoadLoadButtonActionPerformed

    private void IXR3LoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IXR3LoadButtonActionPerformed
        // TODO add your handling code here:
        main_CPU.setRegisterValue("X3", Arrays.copyOfRange(in_button_array, 0, 16));

    }//GEN-LAST:event_IXR3LoadButtonActionPerformed

    private void IXR2LoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IXR2LoadButtonActionPerformed
        // TODO add your handling code here:
        main_CPU.setRegisterValue("X2", Arrays.copyOfRange(in_button_array, 0, 16));
    }//GEN-LAST:event_IXR2LoadButtonActionPerformed

    private void IXR1LoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IXR1LoadButtonActionPerformed
        // TODO add your handling code here:
        main_CPU.setRegisterValue("X1", Arrays.copyOfRange(in_button_array, 0, 16));
    }//GEN-LAST:event_IXR1LoadButtonActionPerformed

    private void GPR3LoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPR3LoadButtonActionPerformed
        // TODO add your handling code here:
        main_CPU.setRegisterValue("GPR3", Arrays.copyOfRange(in_button_array, 0, 16));
    }//GEN-LAST:event_GPR3LoadButtonActionPerformed

    private void GPR2LoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPR2LoadButtonActionPerformed
        // TODO add your handling code here:
        main_CPU.setRegisterValue("GPR2", Arrays.copyOfRange(in_button_array, 0, 16));
    }//GEN-LAST:event_GPR2LoadButtonActionPerformed

    private void GPR1LoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPR1LoadButtonActionPerformed
        // TODO add your handling code here:
        main_CPU.setRegisterValue("GPR1", Arrays.copyOfRange(in_button_array, 0, 16));
    }//GEN-LAST:event_GPR1LoadButtonActionPerformed

    private void GPR0LoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPR0LoadButtonActionPerformed
        // TODO add your handling code here:
        main_CPU.setRegisterValue("GPR0", Arrays.copyOfRange(in_button_array, 0, 16));
    }//GEN-LAST:event_GPR0LoadButtonActionPerformed

    private void MBRLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MBRLoadButtonActionPerformed
        // TODO add your handling code here:
        main_CPU.setRegisterValue("MBR", Arrays.copyOfRange(in_button_array, 0, 16));
    }//GEN-LAST:event_MBRLoadButtonActionPerformed

    private void IRLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IRLoadButtonActionPerformed
        // TODO add your handling code here:
        main_CPU.setRegisterValue("IR", Arrays.copyOfRange(in_button_array, 0, 16));
    }//GEN-LAST:event_IRLoadButtonActionPerformed

    private void MARLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MARLoadButtonActionPerformed
        // TODO add your handling code here:
        main_CPU.setRegisterValue("MAR", Arrays.copyOfRange(in_button_array, 4, 16));
    }//GEN-LAST:event_MARLoadButtonActionPerformed

    private void PCLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCLoadButtonActionPerformed
        // TODO add your handling code here:
        main_CPU.setRegisterValue("PC", Arrays.copyOfRange(in_button_array,4, 16));
    }//GEN-LAST:event_PCLoadButtonActionPerformed

    private void HaltButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HaltButtonActionPerformed
        // TODO add your handling code here:
        int [] msg = new int[]{1};
        main_CPU.setRegisterValue("HLT",msg);
    }//GEN-LAST:event_HaltButtonActionPerformed

    private void SingleStepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingleStepButtonActionPerformed
        // TODO add your handling code here:
        main_CPU.execute("single");
    }//GEN-LAST:event_SingleStepButtonActionPerformed

    private void STLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STLoadButtonActionPerformed
        // Set Memory(MAR) to MBR
        int[] cur_MAR = main_CPU.getRegisterValue("MAR");
        int trans_MAR = main_CPU.binaryToInt(cur_MAR);
        main_CPU.setMemoryValue(trans_MAR, main_CPU.getRegisterValue("MBR"));

    }//GEN-LAST:event_STLoadButtonActionPerformed

    private void STPLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STPLoadButtonActionPerformed
        // Set Memory(MAR) to MBR
        int[] cur_MAR = main_CPU.getRegisterValue("MAR");
        int trans_MAR = main_CPU.binaryToInt(cur_MAR);
        main_CPU.setMemoryValue(trans_MAR, main_CPU.getRegisterValue("MBR"));
        // Increment MAR by 1
        trans_MAR = trans_MAR + 1;
        int[] new_MAR = main_CPU.intToBinaryArrayShort(Integer.toBinaryString(trans_MAR));
        main_CPU.setRegisterValue("MAR", new_MAR);
    }//GEN-LAST:event_STPLoadButtonActionPerformed

    private void IPLLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IPLLoadButtonActionPerformed
        
// TODO add your handling code here:
        try {
            // TODO add your handling code here:
            main_CPU.loadFileIntoMemory();
        } catch (IOException ex) {
            Logger.getLogger(MachineSimulator.class.getName()).log(Level.SEVERE, null, ex);
        }
        int[] default_PC_loc = new int[]{0,0,0,0,0,0,0,1,0,1,0,0};
        main_CPU.setRegisterValue("PC",default_PC_loc);
         PrinterTextArea.append("Loading from CARD.txt:\n");
         try {
        Thread.sleep(1000); // wait for 100 milliseconds
    } catch (InterruptedException e) {
        e.printStackTrace();
    }
        loadTextIntoMemory();
    }//GEN-LAST:event_IPLLoadButtonActionPerformed

    private void toggle9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggle9ActionPerformed
        // TODO add your handling code here:
        if (in_button_array[6] == 0){
            in_button_array[6] = 1;
        } else{
            in_button_array[6] = 0;
        }
    }//GEN-LAST:event_toggle9ActionPerformed

    private void toggle7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggle7ActionPerformed
        // TODO add your handling code here:
        if (in_button_array[8] == 0){
            in_button_array[8] = 1;
        } else{
            in_button_array[8] = 0;
        }
    }//GEN-LAST:event_toggle7ActionPerformed

    private void toggle8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggle8ActionPerformed
        // TODO add your handling code here:
        if (in_button_array[7] == 0){
            in_button_array[7] = 1;
        } else{
            in_button_array[7] = 0;
        }
    }//GEN-LAST:event_toggle8ActionPerformed

    private void toggle6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggle6ActionPerformed
        // TODO add your handling code here:
        if (in_button_array[9] == 0){
            in_button_array[9] = 1;
        } else{
            in_button_array[9] = 0;
        }
    }//GEN-LAST:event_toggle6ActionPerformed

    private void toggle5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggle5ActionPerformed
        // TODO add your handling code here:
        if (in_button_array[10] == 0){
            in_button_array[10] = 1;
        } else{
            in_button_array[10] = 0;
        }
    }//GEN-LAST:event_toggle5ActionPerformed

    private void toggle11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggle11ActionPerformed
        // TODO add your handling code here:
        if (in_button_array[4] == 0){
            in_button_array[4] = 1;
        } else{
            in_button_array[4] = 0;
        }
    }//GEN-LAST:event_toggle11ActionPerformed

    private void toggle10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggle10ActionPerformed
        // TODO add your handling code here:
        if (in_button_array[5] == 0){
            in_button_array[5] = 1;
        } else{
            in_button_array[5] = 0;
        }
    }//GEN-LAST:event_toggle10ActionPerformed

    private void toggle12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggle12ActionPerformed
        // TODO add your handling code here:
        if (in_button_array[3] == 0){
            in_button_array[3] = 1;
        } else{
            in_button_array[3] = 0;
        }
    }//GEN-LAST:event_toggle12ActionPerformed

    private void toggle14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggle14ActionPerformed
        // TODO add your handling code here:
        if (in_button_array[1] == 0){
            in_button_array[1] = 1;
        } else{
            in_button_array[1] = 0;
        }
    }//GEN-LAST:event_toggle14ActionPerformed

    private void toggle13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggle13ActionPerformed
        // TODO add your handling code here:
        if (in_button_array[2] == 0){
            in_button_array[2] = 1;
        } else{
            in_button_array[2] = 0;
        }
    }//GEN-LAST:event_toggle13ActionPerformed

    private void toggle15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggle15ActionPerformed
        // TODO add your handling code here:
        if (in_button_array[0] == 0){
            in_button_array[0] = 1;
        } else{
            in_button_array[0] = 0;
        }
    }//GEN-LAST:event_toggle15ActionPerformed

    private void toggle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggle4ActionPerformed
        // TODO add your handling code here:
         if (in_button_array[11] == 0){
            in_button_array[11] = 1;
        } else{
            in_button_array[11] = 0;
        }
    }//GEN-LAST:event_toggle4ActionPerformed

    private void toggle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggle3ActionPerformed
        // TODO add your handling code here:
         if (in_button_array[12] == 0){
            in_button_array[12] = 1;
        } else{
            in_button_array[12] = 0;
        }
    }//GEN-LAST:event_toggle3ActionPerformed

    private void toggle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggle2ActionPerformed
        // TODO add your handling code here:
        if (in_button_array[13] == 0){
            in_button_array[13] = 1;
        } else{
            in_button_array[13] = 0;
        }
    }//GEN-LAST:event_toggle2ActionPerformed

    private void toggle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggle1ActionPerformed
        // TODO add your handling code here:
        if (in_button_array[14] == 0){
            in_button_array[14] = 1;
        } else{
            in_button_array[14] = 0;
        }
    }//GEN-LAST:event_toggle1ActionPerformed

    private void toggle0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggle0ActionPerformed
        // TODO add your handling code here:
        if (in_button_array[15] == 0){
            in_button_array[15] = 1;
        } else{
            in_button_array[15] = 0;
        }
    }//GEN-LAST:event_toggle0ActionPerformed

    private void KeyboardTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeyboardTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KeyboardTextFieldActionPerformed

    private void KeyboardReadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeyboardReadButtonActionPerformed
        // TODO add your handling code here:
        search = KeyboardTextField.getText();
        ConsoleTextField.setText(search);
    }//GEN-LAST:event_KeyboardReadButtonActionPerformed

    private void ConsoleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsoleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsoleTextFieldActionPerformed

    private void PCTextfFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCTextfFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PCTextfFieldActionPerformed

    private void GPR1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPR1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GPR1TextFieldActionPerformed

    /* 
    Function to Update Values of the registers
    IN: N/A
    OUT: N/A
    */
    public void updateRegisters(){
        
        // Update PC
        int[] tmp_array;
        tmp_array = main_CPU.getRegisterValue("PC");
        PCTextfField.setText(formatText(tmp_array));
        // Update CC
        tmp_array = main_CPU.getRegisterValue("CC");
        CCTextField.setText(formatText(tmp_array));
        // Update MAR and Associated Display
        tmp_array = main_CPU.getRegisterValue("MAR");
        MARTextField.setText(formatText(tmp_array));
        updateMemoryDisplay();
        // Update MBR
        tmp_array = main_CPU.getRegisterValue("MBR");
        MBRTextField.setText(formatText(tmp_array));
        // Update IR
        tmp_array = main_CPU.getRegisterValue("IR");
        IRTextField.setText(formatText(tmp_array));
        // Update MFR
        tmp_array = main_CPU.getRegisterValue("MFR");
        MFRTextField.setText(formatText(tmp_array));
        // Update X1
        tmp_array = main_CPU.getRegisterValue("X1");
        IXR1TextField.setText(formatText(tmp_array));
        // Update X2
        tmp_array = main_CPU.getRegisterValue("X2");
        IXR2TextField.setText(formatText(tmp_array));
        // Update X3
        tmp_array = main_CPU.getRegisterValue("X3");
        IXR3TextField.setText(formatText(tmp_array));
        // Update GPR0
        tmp_array = main_CPU.getRegisterValue("GPR0");
        GPR0TextField.setText(formatText(tmp_array));
        // Update GPR1
        tmp_array = main_CPU.getRegisterValue("GPR1");
        GPR1TextField.setText(formatText(tmp_array));
        // Update GPR2
        tmp_array = main_CPU.getRegisterValue("GPR2");
        GPR2TextField.setText(formatText(tmp_array));
        // Update GPR3
        tmp_array = main_CPU.getRegisterValue("GPR3");
        GPR3TextField.setText(formatText(tmp_array));
    }
    
    /* 
    Function to update the display with values stored in memory at location MAR
    IN: N/A
    OUT: N/A
    */
    public void updateMemoryDisplay(){
        // Set values for current Mar Location
        int[] tmp_array;
        int[] cur_MAR = main_CPU.getRegisterValue("MAR");
        int trans_MAR = main_CPU.binaryToInt(cur_MAR);
        tmp_array = main_CPU.getMemoryValue(trans_MAR);
        Mem0ValueTextField.setText(formatText(tmp_array));
        Mem0RowTextField.setText(Integer.toString(trans_MAR));
        
        // Get MAR + 1
        trans_MAR = trans_MAR + 1;
        tmp_array = main_CPU.getMemoryValue(trans_MAR);
        Mem1ValueTextField.setText(formatText(tmp_array));
        Mem1RowTextField.setText(Integer.toString(trans_MAR));
        
        // Get MAR + 2
        trans_MAR = trans_MAR + 1;
        tmp_array = main_CPU.getMemoryValue(trans_MAR);
        Mem2ValueTextField.setText(formatText(tmp_array));
        Mem2RowTextField.setText(Integer.toString(trans_MAR));
        
        if (main_CPU.binaryToInt(cur_MAR) > 2){
            // Get MAR - 1
            trans_MAR = trans_MAR - 3;
            tmp_array = main_CPU.getMemoryValue(trans_MAR);
            Mem_1ValueTextField.setText(formatText(tmp_array));
            Mem_1RowTextField.setText(Integer.toString(trans_MAR));

            // Get MAR - 2
            trans_MAR = trans_MAR - 1;
            tmp_array = main_CPU.getMemoryValue(trans_MAR);
            Mem_2ValueTextField.setText(formatText(tmp_array));
            Mem_2RowTextField.setText(Integer.toString(trans_MAR));
        }else{
            int[] blank_value = new int[]{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
            Mem_1ValueTextField.setText(formatText(blank_value));
            Mem_1RowTextField.setText(Integer.toString(0));
            Mem_2ValueTextField.setText(formatText(blank_value));
            Mem_2RowTextField.setText(Integer.toString(0));
        }
    }
    
    /* 
    Function to convert the text in the console keyboard into an input
    IN: N/A
    OUT: N/A
    */
    public void updateKeyboard(){
        int input = Integer.parseInt(KeyboardTextField.getText());
        int[] converted_input = main_CPU.intToBinaryArray(Integer.toBinaryString(input));
        
        
        main_CPU.setRegisterValue("KEYBOARD",converted_input);
        
        int[] in_value = main_CPU.getRegisterValue("KEYBOARD");
        switch( main_CPU.getRegisterValue("IOWAIT")[0]){
            case 1:
                main_CPU.setRegisterValue("GPR0",in_value);
                break;
            case 2:
                main_CPU.setRegisterValue("GPR1",in_value);
                break;
            case 3:
                main_CPU.setRegisterValue("GPR2",in_value);
                break;
            case 4:
                main_CPU.setRegisterValue("GPR3",in_value);
                break;
        }
        System.out.println(formatText(converted_input));
    }
    
    /* 
    Function to add text to the console printer
    IN: N/A
    OUT: N/A
    */
    public void updatePrinter(){
        // add value to print area
        PrinterTextArea.append(formatText(main_CPU.getRegisterValue("KEYBOARD")));
        PrinterTextArea.append("\n");
        System.out.println(formatText(main_CPU.getRegisterValue("KEYBOARD")));
        // Flush printer
        int[] Reset_large = new int[]{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
        main_CPU.setRegisterValue("KEYBOARD", Reset_large);
    }
    
    static String reverse(String input){
        char[] a = input.toCharArray();
        int l, r = 0;
        r = a.length - 1;
 
        for (l = 0; l < r; l++, r--)
        {
            // Swap values of l and r
            char temp = a[l];
            a[l] = a[r];
            a[r] = temp;
        }
        return String.valueOf(a);
    }
     


    public void loadTextIntoMemory() {

        // The path of the text file to read
        String filePath = System.getProperty("user.dir") + "/CARD.txt";

        // A StringBuilder to store the contents of the file
        StringBuilder stringBuilder = new StringBuilder();

        try {
            // Create a FileReader object to read the file
            FileReader fileReader = new FileReader(filePath);

            // Create a BufferedReader object to read the FileReader object
            BufferedReader bufferedReader = new BufferedReader(fileReader);

            // Read each line of the file and append it to the StringBuilder
            String line;
            while ((line = bufferedReader.readLine()) != null) {
                stringBuilder.append(line);
                stringBuilder.append("\n"); // Add a newline character after each line
            }

            // Close the BufferedReader and FileReader objects
            bufferedReader.close();
            fileReader.close();

        } catch (IOException e) {
            e.printStackTrace();
        }

        // Convert the StringBuilder to a String and store it in a variable
        
       
//         PrinterTextArea.append("Loaded from CARD.txt:\n");
        search_text = stringBuilder.toString();
        
       
       PrinterTextArea.append(search_text);
         


    }
    
    public void proccessText() {
        
        String word = search;
        
        PrinterTextArea.append("Search for: "+search+"\n");
        // Split the paragraph into an array of words
        String[] words = search_text.replaceAll("[.]", "").split(" ");
        
        boolean found = false;
        for (int i = 0; i < words.length; i++) {
            int decimalValue = i;
            String binaryValue = decimalToBinary16(decimalValue);
            int[] binaryArray = new int[binaryValue.length()];

            for (int j = 0; j < binaryValue.length(); j++) {
                binaryArray[j] = Character.getNumericValue(binaryValue.charAt(j));
            }
            int[] one_array = new int[]{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1};
            main_CPU.setRegisterValue("GPR1", binaryArray);

            int[] start_register_value = main_CPU.getRegisterValue("GPR1");
            int[] new_register_value = null;
            // If the word is found, print a message and set the "found" flag to true
            if(words[i].equalsIgnoreCase(word)) {
                PrinterTextArea.append("The word '" + word + "' was found at position " + i + ".");
                found = true;
                break;
            }
    }
    // If the word was not found, print a message
    if (!found) {
        PrinterTextArea.append("The word '" + word + "' was not found.");
        int[] one_array = new int[]{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
            main_CPU.setRegisterValue("GPR1", one_array);
    }

    }
public static String decimalToBinary16(int decimal) {
    String binary = Integer.toBinaryString(decimal);
    int length = binary.length();
    if (length > 16) {
        throw new IllegalArgumentException("Decimal value is too large for a 16-bit binary value.");
    } else if (length < 16) {
        // pad the binary string with leading zeros if it is shorter than 16 bits
        binary = String.format("%0" + (16 - length) + "d", 0) + binary;
    }
    return binary;
}
    
    /* 
    Function to format int[] values for display on the GUI
    IN: int[] array representing the value of a register
    OUT: String representing the converted value
    */
    public String formatText(int[] arr){
        String res = Arrays.toString(arr).replaceAll("[\\[\\],]", "");
        return res;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MachineSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MachineSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MachineSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MachineSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MachineSimulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CCTextField;
    private javax.swing.JTextField ConsoleTextField;
    private javax.swing.JButton GPR0LoadButton;
    private javax.swing.JTextField GPR0TextField;
    private javax.swing.JButton GPR1LoadButton;
    private javax.swing.JTextField GPR1TextField;
    private javax.swing.JButton GPR2LoadButton;
    private javax.swing.JTextField GPR2TextField;
    private javax.swing.JButton GPR3LoadButton;
    private javax.swing.JTextField GPR3TextField;
    private javax.swing.JToggleButton HaltButton;
    private javax.swing.JButton IPLLoadButton;
    private javax.swing.JButton IRLoadButton;
    private javax.swing.JTextField IRTextField;
    private javax.swing.JButton IXR1LoadButton;
    private javax.swing.JTextField IXR1TextField;
    private javax.swing.JButton IXR2LoadButton;
    private javax.swing.JTextField IXR2TextField;
    private javax.swing.JButton IXR3LoadButton;
    private javax.swing.JTextField IXR3TextField;
    private javax.swing.JButton KeyboardReadButton;
    private javax.swing.JTextField KeyboardTextField;
    private javax.swing.JButton LoadLoadButton;
    private javax.swing.JButton MARLoadButton;
    private javax.swing.JTextField MARTextField;
    private javax.swing.JButton MBRLoadButton;
    private javax.swing.JTextField MBRTextField;
    private javax.swing.JTextField MFRTextField;
    private javax.swing.JTextField Mem0RowTextField;
    private javax.swing.JTextField Mem0ValueTextField;
    private javax.swing.JTextField Mem1RowTextField;
    private javax.swing.JTextField Mem1ValueTextField;
    private javax.swing.JTextField Mem2RowTextField;
    private javax.swing.JTextField Mem2ValueTextField;
    private javax.swing.JTextField Mem_1RowTextField;
    private javax.swing.JTextField Mem_1ValueTextField;
    private javax.swing.JTextField Mem_2RowTextField;
    private javax.swing.JTextField Mem_2ValueTextField;
    private javax.swing.JButton PCLoadButton;
    private javax.swing.JTextField PCTextfField;
    private javax.swing.JTextArea PrinterTextArea;
    private javax.swing.JToggleButton ResetButton;
    private javax.swing.JButton RunButton;
    private javax.swing.JButton STLoadButton;
    private javax.swing.JButton STPLoadButton;
    private javax.swing.JButton SingleStepButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton toggle0;
    private javax.swing.JToggleButton toggle1;
    private javax.swing.JToggleButton toggle10;
    private javax.swing.JToggleButton toggle11;
    private javax.swing.JToggleButton toggle12;
    private javax.swing.JToggleButton toggle13;
    private javax.swing.JToggleButton toggle14;
    private javax.swing.JToggleButton toggle15;
    private javax.swing.JToggleButton toggle2;
    private javax.swing.JToggleButton toggle3;
    private javax.swing.JToggleButton toggle4;
    private javax.swing.JToggleButton toggle5;
    private javax.swing.JToggleButton toggle6;
    private javax.swing.JToggleButton toggle7;
    private javax.swing.JToggleButton toggle8;
    private javax.swing.JToggleButton toggle9;
    // End of variables declaration//GEN-END:variables
}
