/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author shahin
 * 
 * Main class that drives GUI. This file creates a CPU object 
 * and runs the computer by making repeated calls to that object.
 */

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;

import javax.swing.Timer;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;

public class MachineSimulator extends javax.swing.JFrame {
    
    // Global Vars
    CPU main_CPU;
    int[] in_button_array = new int[]{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
    int[] default_PC_loc = new int[]{0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0};
    boolean run_check = false;
    
    
    /* 
    Function that runs the gui and CPU
    IN: N/A
    OUT: N/A
    */
    public MachineSimulator() {
        initComponents();
        main_CPU = new CPU();
        int[] tmp_val = {0,0,0,0,0,0,0,0,1,0,1,0};
        main_CPU.setRegisterValue("PC",tmp_val);
        new Timer(delay, taskPerformer).start();
    }
    
    // Main loop of the program that runs every 500 mil
    int delay = 500; //milliseconds
    ActionListener taskPerformer = new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            
            // Update Registers for display
            updateRegisters();
            
            // Check if machine is set to run
            if (run_check){
                main_CPU.execute("single");
                // If running, check if halt flag is raised
                if (main_CPU.getRegisterValue("HLT")[0] == 1){
                    run_check = false;
                    int [] msg = new int[]{0};
                    main_CPU.setRegisterValue("HLT",msg);
                }
            }
        }
    };
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        GPR0TextField = new javax.swing.JTextField();
        GPR1TextField = new javax.swing.JTextField();
        GPR2TextField = new javax.swing.JTextField();
        GPR3TextField = new javax.swing.JTextField();
        IXR1TextField = new javax.swing.JTextField();
        IXR2TextField = new javax.swing.JTextField();
        IXR3TextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        PCTextfField = new javax.swing.JTextField();
        MARTextField = new javax.swing.JTextField();
        MBRTextField = new javax.swing.JTextField();
        IRTextField = new javax.swing.JTextField();
        MFRTextField = new javax.swing.JTextField();
        IPLLoadButton = new javax.swing.JButton();
        STPLoadButton = new javax.swing.JButton();
        STLoadButton = new javax.swing.JButton();
        FifteenButton = new javax.swing.JButton();
        FourteenButton = new javax.swing.JButton();
        ThirteenButton = new javax.swing.JButton();
        TweleveButton = new javax.swing.JButton();
        ElevenButton = new javax.swing.JButton();
        TenButton = new javax.swing.JButton();
        NineButton = new javax.swing.JButton();
        EightButton = new javax.swing.JButton();
        FiveButton = new javax.swing.JButton();
        SevenButton = new javax.swing.JButton();
        SixButton = new javax.swing.JButton();
        ZeroButton = new javax.swing.JButton();
        OneButton = new javax.swing.JButton();
        TwoButton = new javax.swing.JButton();
        ThreeButton = new javax.swing.JButton();
        FourButton = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        SingleStepButton = new javax.swing.JButton();
        HaltButton = new javax.swing.JToggleButton();
        PCLoadButton = new javax.swing.JButton();
        MARLoadButton = new javax.swing.JButton();
        IRLoadButton = new javax.swing.JButton();
        MBRLoadButton = new javax.swing.JButton();
        GPR0LoadButton = new javax.swing.JButton();
        GPR1LoadButton = new javax.swing.JButton();
        GPR2LoadButton = new javax.swing.JButton();
        GPR3LoadButton = new javax.swing.JButton();
        IXR1LoadButton = new javax.swing.JButton();
        IXR2LoadButton = new javax.swing.JButton();
        IXR3LoadButton = new javax.swing.JButton();
        CCTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        LoadLoadButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JToggleButton();
        Mem_2ValueTextField = new javax.swing.JTextField();
        Mem_1ValueTextField = new javax.swing.JTextField();
        Mem0ValueTextField = new javax.swing.JTextField();
        Mem1ValueTextField = new javax.swing.JTextField();
        Mem2ValueTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Mem_2RowTextField = new javax.swing.JTextField();
        Mem_1RowTextField = new javax.swing.JTextField();
        Mem1RowTextField = new javax.swing.JTextField();
        Mem2RowTextField = new javax.swing.JTextField();
        Mem0RowTextField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        RunButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("GPR 0");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setText("GPR 1");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setText("GPR 2");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setText("GPR 3");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setText("IXR 1");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setText("IXR 2");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel7.setText("IXR 3");

        GPR0TextField.setText("jTextField1");

        GPR1TextField.setText("jTextField2");

        GPR2TextField.setText("jTextField3");

        GPR3TextField.setText("jTextField4");

        IXR1TextField.setText("jTextField5");

        IXR2TextField.setText("jTextField6");

        IXR3TextField.setText("jTextField7");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel8.setText("PC");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel9.setText("MAR");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel10.setText("MBR");

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel11.setText("IR");

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel12.setText("MFR");

        PCTextfField.setText("jTextField8");

        MARTextField.setText("jTextField9");

        MBRTextField.setText("jTextField10");

        IRTextField.setText("jTextField11");

        MFRTextField.setText("jTextField12");

        IPLLoadButton.setText("IPL");
        IPLLoadButton.setActionCommand("Store");
        IPLLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IPLLoadButtonActionPerformed(evt);
            }
        });

        STPLoadButton.setActionCommand("ST+");
        STPLoadButton.setLabel("ST+");
        STPLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STPLoadButtonActionPerformed(evt);
            }
        });

        STLoadButton.setLabel("Store");
        STLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STLoadButtonActionPerformed(evt);
            }
        });

        FifteenButton.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        FifteenButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FifteenButton.setLabel("15");
        FifteenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FifteenButtonActionPerformed(evt);
            }
        });

        FourteenButton.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        FourteenButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FourteenButton.setLabel("14");
        FourteenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourteenButtonActionPerformed(evt);
            }
        });

        ThirteenButton.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        ThirteenButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ThirteenButton.setLabel("13");
        ThirteenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThirteenButtonActionPerformed(evt);
            }
        });

        TweleveButton.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        TweleveButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TweleveButton.setLabel("12");
        TweleveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TweleveButtonActionPerformed(evt);
            }
        });

        ElevenButton.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        ElevenButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ElevenButton.setLabel("11");
        ElevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElevenButtonActionPerformed(evt);
            }
        });

        TenButton.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        TenButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TenButton.setLabel("10");
        TenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TenButtonActionPerformed(evt);
            }
        });

        NineButton.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        NineButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NineButton.setLabel("9");
        NineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NineButtonActionPerformed(evt);
            }
        });

        EightButton.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        EightButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EightButton.setLabel("8");
        EightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EightButtonActionPerformed(evt);
            }
        });

        FiveButton.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        FiveButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FiveButton.setLabel("5");
        FiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiveButtonActionPerformed(evt);
            }
        });

        SevenButton.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        SevenButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SevenButton.setLabel("7");
        SevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SevenButtonActionPerformed(evt);
            }
        });

        SixButton.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        SixButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SixButton.setLabel("6");
        SixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixButtonActionPerformed(evt);
            }
        });

        ZeroButton.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        ZeroButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ZeroButton.setLabel("0");
        ZeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZeroButtonActionPerformed(evt);
            }
        });

        OneButton.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        OneButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        OneButton.setLabel("1");
        OneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneButtonActionPerformed(evt);
            }
        });

        TwoButton.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        TwoButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TwoButton.setLabel("2");
        TwoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoButtonActionPerformed(evt);
            }
        });

        ThreeButton.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        ThreeButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ThreeButton.setLabel("3");
        ThreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeButtonActionPerformed(evt);
            }
        });

        FourButton.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        FourButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FourButton.setLabel("4");
        FourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourButtonActionPerformed(evt);
            }
        });

        jLabel19.setText("Operation");

        jLabel20.setText("GPR");

        jLabel21.setText("IXR");

        jLabel22.setText("I");

        jLabel23.setText("Address");

        SingleStepButton.setLabel("SS");
        SingleStepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingleStepButtonActionPerformed(evt);
            }
        });

        HaltButton.setLabel("Halt");
        HaltButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HaltButtonActionPerformed(evt);
            }
        });

        PCLoadButton.setLabel("Load");
        PCLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCLoadButtonActionPerformed(evt);
            }
        });

        MARLoadButton.setLabel("Load");
        MARLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MARLoadButtonActionPerformed(evt);
            }
        });

        IRLoadButton.setLabel("Load");
        IRLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IRLoadButtonActionPerformed(evt);
            }
        });

        MBRLoadButton.setLabel("Load");
        MBRLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MBRLoadButtonActionPerformed(evt);
            }
        });

        GPR0LoadButton.setLabel("Load");
        GPR0LoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPR0LoadButtonActionPerformed(evt);
            }
        });

        GPR1LoadButton.setLabel("Load");
        GPR1LoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPR1LoadButtonActionPerformed(evt);
            }
        });

        GPR2LoadButton.setLabel("Load");
        GPR2LoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPR2LoadButtonActionPerformed(evt);
            }
        });

        GPR3LoadButton.setLabel("Load");
        GPR3LoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPR3LoadButtonActionPerformed(evt);
            }
        });

        IXR1LoadButton.setLabel("Load");
        IXR1LoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IXR1LoadButtonActionPerformed(evt);
            }
        });

        IXR2LoadButton.setLabel("Load");
        IXR2LoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IXR2LoadButtonActionPerformed(evt);
            }
        });

        IXR3LoadButton.setLabel("Load");
        IXR3LoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IXR3LoadButtonActionPerformed(evt);
            }
        });

        CCTextField.setText("jTextField12");

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel13.setText("CC");

        LoadLoadButton.setText("Load");
        LoadLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadLoadButtonActionPerformed(evt);
            }
        });

        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        Mem_2ValueTextField.setText("jTextField1");

        Mem_1ValueTextField.setText("jTextField2");

        Mem0ValueTextField.setText("jTextField3");

        Mem1ValueTextField.setText("jTextField4");

        Mem2ValueTextField.setText("jTextField5");

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel14.setText("Memory Location - 2");

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel15.setText("Memory Location - 1");

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel16.setText("MAR Location");

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel17.setText("Memory Location + 1");

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel18.setText("Memory Location + 2");

        Mem_2RowTextField.setText("jTextField1");

        Mem_1RowTextField.setText("jTextField1");

        Mem1RowTextField.setText("jTextField1");

        Mem2RowTextField.setText("jTextField1");

        Mem0RowTextField.setText("jTextField1");

        jLabel24.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel24.setText("Mem. Row");

        jLabel25.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel25.setText("Mem. Value");

        jLabel26.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel26.setText("Register Value");

        jLabel27.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel27.setText("Register Value");

        RunButton.setText("Run");
        RunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(FifteenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FourteenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ThirteenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TweleveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ElevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(PCTextfField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PCLoadButton))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IRLoadButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CCTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(5, 5, 5))
                                    .addComponent(jLabel12))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(MARTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(MFRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(MBRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MARLoadButton)
                            .addComponent(MBRLoadButton))))
                .addGap(87, 87, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 491, Short.MAX_VALUE)
                        .addComponent(IPLLoadButton)
                        .addGap(18, 18, 18)
                        .addComponent(STPLoadButton)
                        .addGap(18, 18, 18)
                        .addComponent(STLoadButton)
                        .addGap(18, 18, 18)
                        .addComponent(LoadLoadButton)
                        .addGap(465, 465, 465))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(IXR1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(IXR1LoadButton))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel4)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(GPR3TextField))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(GPR2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel26)
                                                        .addComponent(GPR0TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(GPR1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(GPR0LoadButton)
                                            .addComponent(GPR1LoadButton)
                                            .addComponent(GPR2LoadButton)
                                            .addComponent(GPR3LoadButton)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(IXR2TextField)
                                            .addComponent(IXR3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(IXR2LoadButton)
                                            .addComponent(IXR3LoadButton)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(NineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(SevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(206, 206, 206)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(FourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(OneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ZeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33)
                                        .addComponent(SingleStepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(HaltButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(RunButton)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addGap(21, 21, 21)
                                                .addComponent(Mem_1RowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel18)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Mem2RowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel17)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Mem1RowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel16)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Mem0RowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel14)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel24)
                                                        .addComponent(Mem_2RowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(Mem1ValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(Mem_2ValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Mem2ValueTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(Mem_1ValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Mem0ValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel25))))))
                        .addGap(317, 317, 317))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Mem_2ValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mem_2RowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(Mem_1ValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mem_1RowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Mem0ValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(Mem0RowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Mem1ValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(Mem1RowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(Mem2ValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mem2RowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(141, 141, 141)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IPLLoadButton)
                            .addComponent(STPLoadButton)
                            .addComponent(STLoadButton)
                            .addComponent(LoadLoadButton)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel26)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(GPR0TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GPR0LoadButton)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(GPR1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(GPR1LoadButton))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(GPR2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(GPR2LoadButton))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(GPR3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(GPR3LoadButton))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(IXR1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(IXR1LoadButton))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(IXR2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(IXR2LoadButton))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(IXR3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7)
                                        .addComponent(IXR3LoadButton)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(103, 103, 103)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(CCTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(97, 97, 97))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel27)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PCLoadButton)
                                .addComponent(PCTextfField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(IRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(IRLoadButton)
                                .addComponent(jLabel11))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(MARTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(MARLoadButton))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(MBRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(MBRLoadButton))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(MFRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12))
                            .addGap(153, 153, 153))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FifteenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ThirteenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FourteenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TweleveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ElevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ZeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SingleStepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ResetButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RunButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HaltButton)))))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FifteenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FifteenButtonActionPerformed
        // TODO add your handling code here:
        if (in_button_array[0] == 0){
            in_button_array[0] = 1;
        } else{
            in_button_array[0] = 0;
        }
    }//GEN-LAST:event_FifteenButtonActionPerformed

    private void ThirteenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThirteenButtonActionPerformed
        // TODO add your handling code here:
        if (in_button_array[2] == 0){
            in_button_array[2] = 1;
        } else{
            in_button_array[2] = 0;
        }
    }//GEN-LAST:event_ThirteenButtonActionPerformed

    private void TweleveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TweleveButtonActionPerformed
        // TODO add your handling code here:
        if (in_button_array[3] == 0){
            in_button_array[3] = 1;
        } else{
            in_button_array[3] = 0;
        }
    }//GEN-LAST:event_TweleveButtonActionPerformed

    private void TenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TenButtonActionPerformed
        // TODO add your handling code here:
        if (in_button_array[5] == 0){
            in_button_array[5] = 1;
        } else{
            in_button_array[5] = 0;
        }
    }//GEN-LAST:event_TenButtonActionPerformed

    private void NineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NineButtonActionPerformed
        // TODO add your handling code here:
        if (in_button_array[6] == 0){
            in_button_array[6] = 1;
        } else{
            in_button_array[6] = 0;
        }
    }//GEN-LAST:event_NineButtonActionPerformed

    private void FiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiveButtonActionPerformed
        // TODO add your handling code here:
        if (in_button_array[10] == 0){
            in_button_array[10] = 1;
        } else{
            in_button_array[10] = 0;
        }
    }//GEN-LAST:event_FiveButtonActionPerformed

    private void SevenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SevenButtonActionPerformed
        // TODO add your handling code here:
        if (in_button_array[8] == 0){
            in_button_array[8] = 1;
        } else{
            in_button_array[8] = 0;
        }
    }//GEN-LAST:event_SevenButtonActionPerformed

    private void OneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneButtonActionPerformed
        // TODO add your handling code here:
        if (in_button_array[14] == 0){
            in_button_array[14] = 1;
        } else{
            in_button_array[14] = 0;
        }
    }//GEN-LAST:event_OneButtonActionPerformed

    private void TwoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoButtonActionPerformed
        // TODO add your handling code here:
        if (in_button_array[13] == 0){
            in_button_array[13] = 1;
        } else{
            in_button_array[13] = 0;
        }
    }//GEN-LAST:event_TwoButtonActionPerformed

    private void FourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourButtonActionPerformed
        // TODO add your handling code here:
        if (in_button_array[11] == 0){
            in_button_array[11] = 1;
        } else{
            in_button_array[11] = 0;
        }
    }//GEN-LAST:event_FourButtonActionPerformed

    private void SingleStepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingleStepButtonActionPerformed
        // TODO add your handling code here:
        main_CPU.execute("single");
    }//GEN-LAST:event_SingleStepButtonActionPerformed

    private void ZeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZeroButtonActionPerformed
        // TODO add your handling code here:
        if (in_button_array[15] == 0){
            in_button_array[15] = 1;
        } else{
            in_button_array[15] = 0;
        }
    }//GEN-LAST:event_ZeroButtonActionPerformed

    private void ThreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeButtonActionPerformed
        // TODO add your handling code here:
        if (in_button_array[12] == 0){
            in_button_array[12] = 1;
        } else{
            in_button_array[12] = 0;
        }
    }//GEN-LAST:event_ThreeButtonActionPerformed

    private void SixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SixButtonActionPerformed
        // TODO add your handling code here:
        if (in_button_array[9] == 0){
            in_button_array[9] = 1;
        } else{
            in_button_array[9] = 0;
        }
    }//GEN-LAST:event_SixButtonActionPerformed

    private void EightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EightButtonActionPerformed
        // TODO add your handling code here:
        if (in_button_array[7] == 0){
            in_button_array[7] = 1;
        } else{
            in_button_array[7] = 0;
        }
    }//GEN-LAST:event_EightButtonActionPerformed

    private void ElevenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElevenButtonActionPerformed
        // TODO add your handling code here:
        if (in_button_array[4] == 0){
            in_button_array[4] = 1;
        } else{
            in_button_array[4] = 0;
        }
    }//GEN-LAST:event_ElevenButtonActionPerformed

    private void FourteenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourteenButtonActionPerformed
        // TODO add your handling code here:
        if (in_button_array[1] == 0){
            in_button_array[1] = 1;
        } else{
            in_button_array[1] = 0;
        }
    }//GEN-LAST:event_FourteenButtonActionPerformed

    private void PCLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCLoadButtonActionPerformed
        // TODO add your handling code here:
        main_CPU.setRegisterValue("PC", Arrays.copyOfRange(in_button_array,4, 16));
    }//GEN-LAST:event_PCLoadButtonActionPerformed

    private void MARLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MARLoadButtonActionPerformed
        // TODO add your handling code here:
        main_CPU.setRegisterValue("MAR", Arrays.copyOfRange(in_button_array, 4, 16));
    }//GEN-LAST:event_MARLoadButtonActionPerformed

    private void IRLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IRLoadButtonActionPerformed
        // TODO add your handling code here:
        main_CPU.setRegisterValue("IR", Arrays.copyOfRange(in_button_array, 0, 16));
    }//GEN-LAST:event_IRLoadButtonActionPerformed

    private void MBRLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MBRLoadButtonActionPerformed
        // TODO add your handling code here:
        main_CPU.setRegisterValue("MBR", Arrays.copyOfRange(in_button_array, 0, 16));
    }//GEN-LAST:event_MBRLoadButtonActionPerformed

    private void GPR0LoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPR0LoadButtonActionPerformed
        // TODO add your handling code here:
        main_CPU.setRegisterValue("GPR0", Arrays.copyOfRange(in_button_array, 0, 16));
    }//GEN-LAST:event_GPR0LoadButtonActionPerformed

    private void GPR1LoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPR1LoadButtonActionPerformed
        // TODO add your handling code here:
        main_CPU.setRegisterValue("GPR1", Arrays.copyOfRange(in_button_array, 0, 16));
    }//GEN-LAST:event_GPR1LoadButtonActionPerformed

    private void GPR2LoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPR2LoadButtonActionPerformed
        // TODO add your handling code here:
        main_CPU.setRegisterValue("GPR2", Arrays.copyOfRange(in_button_array, 0, 16));
    }//GEN-LAST:event_GPR2LoadButtonActionPerformed

    private void GPR3LoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPR3LoadButtonActionPerformed
        // TODO add your handling code here:
        main_CPU.setRegisterValue("GPR3", Arrays.copyOfRange(in_button_array, 0, 16));
    }//GEN-LAST:event_GPR3LoadButtonActionPerformed

    private void IXR1LoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IXR1LoadButtonActionPerformed
        // TODO add your handling code here:
        main_CPU.setRegisterValue("X1", Arrays.copyOfRange(in_button_array, 0, 16));
    }//GEN-LAST:event_IXR1LoadButtonActionPerformed

    private void IXR2LoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IXR2LoadButtonActionPerformed
        // TODO add your handling code here:
        main_CPU.setRegisterValue("X2", Arrays.copyOfRange(in_button_array, 0, 16));
    }//GEN-LAST:event_IXR2LoadButtonActionPerformed

    private void IXR3LoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IXR3LoadButtonActionPerformed
        // TODO add your handling code here:
        main_CPU.setRegisterValue("X3", Arrays.copyOfRange(in_button_array, 0, 16));
        
    }//GEN-LAST:event_IXR3LoadButtonActionPerformed

    private void STLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STLoadButtonActionPerformed
        // Set Memory(MAR) to MBR
        int[] cur_MAR = main_CPU.getRegisterValue("MAR");
        int trans_MAR = main_CPU.binaryToInt(cur_MAR);
        main_CPU.setMemoryValue(trans_MAR, main_CPU.getRegisterValue("MBR"));
        
    }//GEN-LAST:event_STLoadButtonActionPerformed

    private void IPLLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IPLLoadButtonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            main_CPU.loadFileIntoMemory();
        } catch (IOException ex) {
            Logger.getLogger(MachineSimulator.class.getName()).log(Level.SEVERE, null, ex);
        }
        int[] default_PC_loc = new int[]{0,0,0,0,0,0,1,1,0,0,0,0};
        main_CPU.setRegisterValue("PC",default_PC_loc);
    }//GEN-LAST:event_IPLLoadButtonActionPerformed

    private void LoadLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadLoadButtonActionPerformed
        // Set MBR equal to the value located at MAR in memory
        int[] cur_MAR = main_CPU.getRegisterValue("MAR");
        int trans_MAR = main_CPU.binaryToInt(cur_MAR);
        main_CPU.setRegisterValue("MBR", main_CPU.getMemoryValue(trans_MAR));
    }//GEN-LAST:event_LoadLoadButtonActionPerformed

    private void STPLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STPLoadButtonActionPerformed
        // Set Memory(MAR) to MBR 
        int[] cur_MAR = main_CPU.getRegisterValue("MAR");
        int trans_MAR = main_CPU.binaryToInt(cur_MAR);
        main_CPU.setMemoryValue(trans_MAR, main_CPU.getRegisterValue("MBR"));
        // Increment MAR by 1
        trans_MAR = trans_MAR + 1;
        int[] new_MAR = main_CPU.intToBinaryArrayShort(Integer.toBinaryString(trans_MAR));
        main_CPU.setRegisterValue("MAR", new_MAR);
    }//GEN-LAST:event_STPLoadButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        // Reset registers
        int[] Reset_large = new int[]{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
        int[] Reset_medium = new int[]{0,0,0,0,0,0,0,0,0,0,0,0};
        int[] Reset_small = new int[]{0,0,0,0};
        
        main_CPU.setRegisterValue("IR", Reset_large);
        main_CPU.setRegisterValue("MBR", Reset_large);
        main_CPU.setRegisterValue("X1", Reset_large);
        main_CPU.setRegisterValue("X2", Reset_large);
        main_CPU.setRegisterValue("X3", Reset_large);
        main_CPU.setRegisterValue("GPR3", Reset_large);
        main_CPU.setRegisterValue("GPR0", Reset_large);
        main_CPU.setRegisterValue("GPR1", Reset_large);
        main_CPU.setRegisterValue("GPR2", Reset_large);
        
        main_CPU.setRegisterValue("PC", Reset_medium);
        main_CPU.setRegisterValue("MAR", Reset_medium);
        
        main_CPU.setRegisterValue("CC", Reset_small);
        main_CPU.setRegisterValue("MFR", Reset_small);
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void HaltButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HaltButtonActionPerformed
        // TODO add your handling code here:
        int [] msg = new int[]{1};
        main_CPU.setRegisterValue("HLT",msg);
    }//GEN-LAST:event_HaltButtonActionPerformed

    private void RunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunButtonActionPerformed
        // TODO add your handling code here:
        if (run_check == false){
            run_check = true;
        }else{
            run_check = false;
        }
    }//GEN-LAST:event_RunButtonActionPerformed

    /* 
    Function to Update Values of the registers
    IN: N/A
    OUT: N/A
    */
    public void updateRegisters(){
        
        // Update PC
        int[] tmp_array;
        tmp_array = main_CPU.getRegisterValue("PC");
        PCTextfField.setText(formatText(tmp_array));
        // Update CC
        tmp_array = main_CPU.getRegisterValue("CC");
        CCTextField.setText(formatText(tmp_array));
        // Update MAR and Associated Display
        tmp_array = main_CPU.getRegisterValue("MAR");
        MARTextField.setText(formatText(tmp_array));
        updateMemoryDisplay();
        // Update MBR
        tmp_array = main_CPU.getRegisterValue("MBR");
        MBRTextField.setText(formatText(tmp_array));
        // Update IR
        tmp_array = main_CPU.getRegisterValue("IR");
        IRTextField.setText(formatText(tmp_array));
        // Update MFR
        tmp_array = main_CPU.getRegisterValue("MFR");
        MFRTextField.setText(formatText(tmp_array));
        // Update X1
        tmp_array = main_CPU.getRegisterValue("X1");
        IXR1TextField.setText(formatText(tmp_array));
        // Update X2
        tmp_array = main_CPU.getRegisterValue("X2");
        IXR2TextField.setText(formatText(tmp_array));
        // Update X3
        tmp_array = main_CPU.getRegisterValue("X3");
        IXR3TextField.setText(formatText(tmp_array));
        // Update GPR0
        tmp_array = main_CPU.getRegisterValue("GPR0");
        GPR0TextField.setText(formatText(tmp_array));
        // Update GPR1
        tmp_array = main_CPU.getRegisterValue("GPR1");
        GPR1TextField.setText(formatText(tmp_array));
        // Update GPR2
        tmp_array = main_CPU.getRegisterValue("GPR2");
        GPR2TextField.setText(formatText(tmp_array));
        // Update GPR3
        tmp_array = main_CPU.getRegisterValue("GPR3");
        GPR3TextField.setText(formatText(tmp_array));
    }
    
    /* 
    Function to update the display with values stored in memory at location MAR
    IN: N/A
    OUT: N/A
    */
    public void updateMemoryDisplay(){
        // Set values for current Mar Location
        int[] tmp_array;
        int[] cur_MAR = main_CPU.getRegisterValue("MAR");
        int trans_MAR = main_CPU.binaryToInt(cur_MAR);
        tmp_array = main_CPU.getMemoryValue(trans_MAR);
        Mem0ValueTextField.setText(formatText(tmp_array));
        Mem0RowTextField.setText(Integer.toString(trans_MAR));
        
        // Get MAR + 1
        trans_MAR = trans_MAR + 1;
        tmp_array = main_CPU.getMemoryValue(trans_MAR);
        Mem1ValueTextField.setText(formatText(tmp_array));
        Mem1RowTextField.setText(Integer.toString(trans_MAR));
        
        // Get MAR + 2
        trans_MAR = trans_MAR + 1;
        tmp_array = main_CPU.getMemoryValue(trans_MAR);
        Mem2ValueTextField.setText(formatText(tmp_array));
        Mem2RowTextField.setText(Integer.toString(trans_MAR));
        
        if (main_CPU.binaryToInt(cur_MAR) > 2){
            // Get MAR - 1
            trans_MAR = trans_MAR - 3;
            tmp_array = main_CPU.getMemoryValue(trans_MAR);
            Mem_1ValueTextField.setText(formatText(tmp_array));
            Mem_1RowTextField.setText(Integer.toString(trans_MAR));

            // Get MAR - 2
            trans_MAR = trans_MAR - 1;
            tmp_array = main_CPU.getMemoryValue(trans_MAR);
            Mem_2ValueTextField.setText(formatText(tmp_array));
            Mem_2RowTextField.setText(Integer.toString(trans_MAR));
        }else{
            int[] blank_value = new int[]{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
            Mem_1ValueTextField.setText(formatText(blank_value));
            Mem_1RowTextField.setText(Integer.toString(0));
            Mem_2ValueTextField.setText(formatText(blank_value));
            Mem_2RowTextField.setText(Integer.toString(0));
        }
    }
    
    /* 
    Function to format int[] values for display on the GUI
    IN: int[] array representing the value of a register
    OUT: String representing the converted value
    */
    public String formatText(int[] arr){
        String res = Arrays.toString(arr).replaceAll("[\\[\\],]", "");
        return res;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MachineSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MachineSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MachineSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MachineSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MachineSimulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CCTextField;
    private javax.swing.JButton EightButton;
    private javax.swing.JButton ElevenButton;
    private javax.swing.JButton FifteenButton;
    private javax.swing.JButton FiveButton;
    private javax.swing.JButton FourButton;
    private javax.swing.JButton FourteenButton;
    private javax.swing.JButton GPR0LoadButton;
    private javax.swing.JTextField GPR0TextField;
    private javax.swing.JButton GPR1LoadButton;
    private javax.swing.JTextField GPR1TextField;
    private javax.swing.JButton GPR2LoadButton;
    private javax.swing.JTextField GPR2TextField;
    private javax.swing.JButton GPR3LoadButton;
    private javax.swing.JTextField GPR3TextField;
    private javax.swing.JToggleButton HaltButton;
    private javax.swing.JButton IPLLoadButton;
    private javax.swing.JButton IRLoadButton;
    private javax.swing.JTextField IRTextField;
    private javax.swing.JButton IXR1LoadButton;
    private javax.swing.JTextField IXR1TextField;
    private javax.swing.JButton IXR2LoadButton;
    private javax.swing.JTextField IXR2TextField;
    private javax.swing.JButton IXR3LoadButton;
    private javax.swing.JTextField IXR3TextField;
    private javax.swing.JButton LoadLoadButton;
    private javax.swing.JButton MARLoadButton;
    private javax.swing.JTextField MARTextField;
    private javax.swing.JButton MBRLoadButton;
    private javax.swing.JTextField MBRTextField;
    private javax.swing.JTextField MFRTextField;
    private javax.swing.JTextField Mem0RowTextField;
    private javax.swing.JTextField Mem0ValueTextField;
    private javax.swing.JTextField Mem1RowTextField;
    private javax.swing.JTextField Mem1ValueTextField;
    private javax.swing.JTextField Mem2RowTextField;
    private javax.swing.JTextField Mem2ValueTextField;
    private javax.swing.JTextField Mem_1RowTextField;
    private javax.swing.JTextField Mem_1ValueTextField;
    private javax.swing.JTextField Mem_2RowTextField;
    private javax.swing.JTextField Mem_2ValueTextField;
    private javax.swing.JButton NineButton;
    private javax.swing.JButton OneButton;
    private javax.swing.JButton PCLoadButton;
    private javax.swing.JTextField PCTextfField;
    private javax.swing.JToggleButton ResetButton;
    private javax.swing.JButton RunButton;
    private javax.swing.JButton STLoadButton;
    private javax.swing.JButton STPLoadButton;
    private javax.swing.JButton SevenButton;
    private javax.swing.JButton SingleStepButton;
    private javax.swing.JButton SixButton;
    private javax.swing.JButton TenButton;
    private javax.swing.JButton ThirteenButton;
    private javax.swing.JButton ThreeButton;
    private javax.swing.JButton TweleveButton;
    private javax.swing.JButton TwoButton;
    private javax.swing.JButton ZeroButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
